name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        arch: [aarch64, arm, x86_64]
    timeout-minutes: 600
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "body.md"
        bodyFile: "body.md"
        name: ${{ github.ref_name }}_${{ matrix.arch }}_${{github.sha}}
        token: ${{ secrets.GITHUB_TOKEN }}
